version: '2'
services:
    entiacv2-app:
        image: entiacv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://entiacv2-mysql:3306/entiacv2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    entiacv2-mysql:
        extends:
            file: mysql.yml
            service: entiacv2-mysql
